### ISSUE TITLE
Label on products in product lists

### ISSUE THREAD

**Issue by korablique** [plante-app-team/plante#60]
What does "similar store" means on the labels of products in `ShopProductRangePage`? ("Seen in similar store")

The word "similar" doesn't give an idea that the product was seen in a store with the same name.
It looks like it means "seen in a store, that visually looks similar" or something like that.

We should try the label: `"Seen in other <storename> stores"`.

**Comment by cyclomaticcomplexity1981** [comment]
@blazern @korablique i am not sure about the "other stores". Maybe here we also should use the store name. because "other" can refer to any store while similar still refers to a store like the one you are in.

"Seen in other Lidl"
"Seen in other Aldi"

**Comment by blazern** [comment]
> @blazern @korablique i am not sure about the "other stores". Maybe here we also should use the store name. because "other" can refer to any store while similar still refers to a store like the one you are in.
> 
> "Seen in other Lidl" "Seen in other Aldi"

Yes, that's what was meant by the description!
Github has hidden the `<storename>` piece so it looked wrong.
I think `"Seen in other <storename>"` should also be fine if you would like that.
