### ISSUE TITLE
Separate ProgressBarWithHints into 2 separate widgets

### ISSUE THREAD

**Issue by blazern** [plante-app-team/plante#79]
**Hints should be at the top:**
![image](https://user-images.githubusercontent.com/3338378/147466713-1097c62f-25c5-459d-b209-67757b2a7318.png)

**Progress bar should be at the bottom:**
![image](https://user-images.githubusercontent.com/3338378/147466744-0159acc4-f038-461a-9477-77b42bb10e0c.png)

Figma: https://www.figma.com/file/lHqzwSaWfsBiWNj9iyOaoh/plante-UI?node-id=2194%3A42214

Because now they're separated, they should be in 2 separate widget with similar logic. E.g. the hints widget can be named `TimedHints`.

We should try to reuse the `GradientSpinner` as a progress bar widget. To reuse it, make it so that it would accept custom `colors` and `borderRadius` in its constructor.
If it's not possible, a new widget should be created with a logic similar to `GradientSpinner`.

The new progress bar widget should be at the bottom of the page.
`TimedHints` should be just below the search bar (find `Column` which contains the search bar in `MapPage`).

**New design should not be applied yet**.

**Comment by cyclomaticcomplexity1981** [comment]
@blazern so if i understand correct the progressbar won't show the progress anymore?

**Comment by blazern** [comment]
> @blazern so if i understand correct the progressbar won't show the progress anymore?

Why not? I think it should keep the progress logic it has right now.
It shows to the user that something is loading, the app hasn't hanged.

**Comment by cyclomaticcomplexity1981** [comment]
@blazern no I agree we should show the progress. So if I understand correctly now, we show a incrementing progressbar, but the colors are gradient. So the closer to finished loading the darker to the end.

**Comment by blazern** [comment]
> @blazern no I agree we should show the progress. So if I understand correctly now, we show a incrementing progressbar, but the colors are gradient. So the closer to finished loading the darker to the end.

Oh you're right, I somehow totally missed that we show specific progresses and it doesn't fit `GradientSpinner`...

**Comment by blazern** [comment]
@cyclomaticcomplexity1981, I talked to Olga - she and Sewa think we should try the hints + infinite progress bar from the design (with how `GradientSpinner` works).

What do you think?
Maybe hints alone will be enough to let our users know the loading hasn't hanged?

**Comment by cyclomaticcomplexity1981** [comment]
@blazern i am still not sure what you mean, infinite, meaning it doesn't show the progress anymore? Like it used to be?

i think i liked to progress better. But we can try and see if the hints are enough.

**Comment by blazern** [comment]
Yes, I mean it wouldn't show progress anymore...
I personally like it with progress better too, but we're implementing someone else's vision, I think we should try to keep it intact :)

Maybe it's a good idea to split the current progress-bar-with-hints into 2 separate classes, but to use only the new hints-class, and to leave the extracted progress-bar not used for now.

And then to use `GradientSpinner` to display infinite progress on the map when something is loading.

This way it would be easy to roll back to an not-infinite progressbar in case we would want that.

**Comment by cyclomaticcomplexity1981** [comment]
@blazern i am confused now, i think the design changed to show progress... So as a first implementation just show the incrementing progressbar at the bottom.

**Comment by blazern** [comment]
> @blazern i am confused now, i think the design changed to show progress... So as a first implementation just show the incrementing progressbar at the bottom.

You're right it did change...
I'm fine with incrementing progressbar :)
